# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 08:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0002_userreview'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabelResultV2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mention_id', models.CharField(max_length=64)),
                ('cur_state', models.IntegerField(default=0)),
                ('is_franchise', models.SmallIntegerField(default=0)),
                ('is_wrong_span', models.SmallIntegerField(default=0)),
                ('biz_id', models.CharField(max_length=64)),
                ('username', models.CharField(max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
