# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 08:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0003_auto_20170605_1617'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserReview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('review_id', models.CharField(max_length=64)),
            ],
        ),
    ]
