# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-05 08:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0004_userreview'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReview',
        ),
    ]
