# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-06-13 09:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yelp', '0005_delete_userreview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='labelresultv2',
            name='is_franchise',
        ),
    ]
